### ISSUE TITLE
CSI 0.1 support

### ISSUE THREAD

**Issue by codenrhoden** [thecodeteam/gocsi#22]
The following tasks must be completed for GoCSI to support CSI [v0.1.0](https://github.com/container-storage-interface/spec/blob/v0.1.0/spec.md):

## Required
- [x] Update the spec interceptor / create new interceptor to validate [field size limits](https://github.com/container-storage-interface/spec/blob/v0.1.0/spec.md#field-size-limits)
- [ ] Update the spec interceptor / create new interceptor to validate the information returned from `GetPluginInfo`
  - [x] Plug-in name should adhere to the SUN naming convention
  - [x] Vendor version should probably be a semantic version
- [x] Validate the Mock SP as v0.1.0 compliant
  - [x] Validate all RPCs return the correct gRPC error codes under the correct conditions via automated tests
- [x] Deprecate and remove the idempotent interceptor as it cannot be the basis for distributed idempotency
- [ ] Create a serial access interceptor (based on etcd) to provide foundation for easy-to-implement idempotency to CSI plug-in developers

## Optional
- [ ] Update / enhance / simplify `csp` 
- [ ] Create documentation / examples around `csp`

The above tasks will be updated with links to specific issues/estimates where appropriate.
